language: node_js

node_js:
  - "10"

script:
  - yarn test
  - export TRAVIS_JOB_ID=507511692
  - export TRAVIS_PULL_REQUEST=3
  - export TRAVIS_BRANCH=master
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls


cache: yarn
